name: base
channels:
  - defaults
the workflow definition at line 23:

```yaml
conda envdependencies:
  - python
  - flake8
  - Flask
  - mysql-connector-python
  - matplotlib
  - requests
  - Jinja2
  - numpy
  update --file environment.yml --name base
