name: currency-etl-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - requests
  - flask 
  - mysql-connector-python 
  - matplotlib
  # add other dependencies as needed