name: Run ETL Script

on: [push]

jobs:
  etl-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: my_ml_env
        auto-activate-base: false

    - name: Run ETL script
      run: |
        conda info --envs
        python etl/etl_script.py