name: CI with Conda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: false
        environment-file: environment.yml
        environment-name: currency-etl-env
        python-version: 3.10

    - name: Install dev tools
      run: |
        conda activate currency-etl-env
        conda install flake8 pytest

    - name: Lint with flake8
      run: |
        conda activate currency-etl-env
        flake8 .

    - name: Test with pytest
      run: |
        conda activate currency-etl-env
        pytest
